export const REQUEST_PETITIONS = 'REQUEST_PETITIONS';
export const RECEIVE_PETITIONS = 'RECEIVE_PETITIONS';

export const REQUEST_PETITION = 'REQUEST_PETITION';
export const RECEIVE_PETITION = 'RECEIVE_PETITION';

export const UPDATE_CURRENT_CITY = 'UPDATE_CURRENT_CITY';
export const CLEAR_CURRENT_CITY = 'CLEAR_CURRENT_CITY';

export const SUBMITTING_PETITION = 'SUBMITTING_PETITION';
export const CREATED_PETITION = 'CREATED_PETITION';
export const PUBLISHED_PETITION = 'PUBLISHED_PETITION';
export const UPDATED_PETITION = 'UPDATED_PETITION';
export const CLEAR_PETITION = 'CLEAR_PETITION';

export const SUBMITTING_SUPPORT = 'SUBMITTING_SUPPORT';
export const SUPPORTED_PETITION = 'SUPPORTED_PETITION';

export const REQUEST_WHOAMI = 'REQUEST_WHOAMI';
export const RECEIVE_WHOAMI = 'RECEIVE_WHOAMI';

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const RECEIVE_LOGOUT = 'RECEIVE_LOGOUT';

export const SHOW_FLASH_MESSAGE = 'SHOW_FLASH_MESSAGE';
export const HIDE_FLASH_MESSAGE = 'HIDE_FLASH_MESSAGE';

export const SHOW_MODAL_WINDOW = 'SHOW_MODAL_WINDOW';
export const HIDE_MODAL_WINDOW = 'HIDE_MODAL_WINDOW';

export const UPDATE_SUGGESTIONS = 'UPDATE_SUGGESTIONS';
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';
export const UPDATE_SUGGESTION_INPUT_VALUE = 'UPDATE_SUGGESTION_INPUT_VALUE';

export const TOGGLE_MOBILE_MENU = 'TOGGLE_MOBILE_MENU';
export const CLOSE_MOBILE_MENU = 'CLOSE_MOBILE_MENU';
export const DESTROY_MOBILE_MENU = 'DESTROY_MOBILE_MENU';

export const REQUEST_OPEN_GRAPH = 'REQUEST_OPEN_GRAPH';
export const RECEIVE_OPEN_GRAPH = 'RECEIVE_OPEN_GRAPH';
