export const REQUEST_PETITION = 'REQUEST_PETITION';
export const RECEIVE_PETITION = 'RECEIVE_PETITION';

export const REQUEST_PETITIONS = 'REQUEST_PETITIONS';
export const RECEIVE_PETITIONS = 'RECEIVE_PETITIONS';

export const SUBMIT_PETITION = 'SUBMIT_PETITION';
export const CREATED_PETITION = 'CREATED_PETITION';
export const UPDATED_PETITION = 'UPDATED_PETITION';
export const PUBLISHED_PETITION = 'PUBLISHED_PETITION';

export const REQUEST_WHOAMI = 'REQUEST_WHOAMI';
export const RECEIVE_WHOAMI = 'RECEIVE_WHOAMI';

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const RECEIVE_LOGOUT = 'RECEIVE_LOGOUT';

export const SHOW_FLASH_MESSAGE = 'SHOW_FLASH_MESSAGE';
export const HIDE_FLASH_MESSAGE = 'HIDE_FLASH_MESSAGE';

export const SHOW_MODAL_WINDOW = 'SHOW_MODAL_WINDOW';
export const HIDE_MODAL_WINDOW = 'HIDE_MODAL_WINDOW';
