export const COUNTER_PLUS = 'COUNTER_PLUS';
export const COUNTER_MINUS = 'COUNTER_MINUS';

export const REQUEST_PETITION = 'REQUEST_PETITION';
export const RECEIVE_PETITION = 'RECEIVE_PETITION';

export const REQUEST_PETITIONS = 'REQUEST_PETITIONS';
export const RECEIVE_PETITIONS = 'RECEIVE_PETITIONS';

export const SUBMIT_PETITION = 'SUBMIT_PETITION';
export const CREATED_PETITION = 'CREATED_PETITION';
